DESIGN_NAME: picorv32a
VERILOG_FILES:
  - dir::src/picorv32a.v
CLOCK_PORT: clk
CLOCK_PERIOD: 24.73
SDC_FILE: dir::src/picorv32a.sdc
FP_SIZING: relative
FP_CORE_UTIL: 35
PL_TARGET_DENSITY_PCT: 40
SYNTH_STRATEGY: DELAY 1
SYNTH_SIZING: true
MAX_FANOUT_CONSTRAINT: 6
GRT_ADJUSTMENT: 0.1
RUN_HEURISTIC_DIODE_INSERTION: true
DESIGN_REPAIR_MAX_WIRE_LENGTH: 800
GRT_REPAIR_ANTENNAS: true
